emberjs/ember-inflector

package.json
Without this change, Ember CLI 0.2.0 will have the following warning for
all ember-inflector + ember-cli users:
```
The package `ember-inflector` is not a properly formatted package, we have used a fallback lookup
to resolve it at `/some-path/goes/here/node_modules/ember-inflector`. This is generally caused by
an addon not having a `main` entry point (or `index.js`).
```
=> Add main entry point for package.json.

package.json
now it should be `addon/index.js` or we remove the main property because we have the `index.js`:
> This is generally caused by an addon not having a `main` entry point (or `index.js`).
=> fix package.json main

package.json
Just want to get rid of this little error message:
npm WARN package.json ember-inflector@1.6.0 No repository field.
=> Add the Repository field to Package.json

tests/unit/inflector-test.js
This is related to #79, and tests for possible future regressions in the now-correct behavior. All tests still pass, no release necessary.
=> Add tests for known previous irregular pluralization issue.

addon/lib/system/inflector.js, bower.json, package.json, tests/unit/inflector-test.js
=> Corrected behaviour where words that contain uncountable subwords were being treated as uncountable words

addon/lib/system/inflector.js
The regex `[_/-\s]` will cause error "Invalid range in character set" because it creates a range between the `/` and the `\s` characters. The hyphen needs to be escaped or moved to the end. Problem was observed in IE8, Firefox 14, and 24.
Related: http://stackoverflow.com/questions/23496973/invalid-range-in-character-class-regex-firefox
=> Fixed regex that resulted in an invalid range in older browsers

addon/lib/helpers/pluralize.js, addon/lib/helpers/singularize.js
The singularize and pluralize helpers previously imported the
helpers previously without a default Ember Inflector instance,
which would cause issues for Ember CLI users.
refs GH-74
=> [bugfix release] fix using helpers without default Inflector

.npmignore, .watchmanconfig, bower.json, config/ember-try.js, config/environment.js, ember-cli-build.js, package.json, tests/dummy/app/app.js, tests/dummy/app/router.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/resolver.js, tests/helpers/start-app.js, tests/index.html
- Bumps ember-cli to version 1.13.3
- Also, not sure why, but this fixes the test failures that were occurring with ember-beta and ember-canary that @fivetanley brought up in https://github.com/stefanpenner/ember-inflector/pull/96. No time to look into it further right now :tired_face:
=> Bump ember-cli to version 1.13.13

addon/lib/helpers/pluralize.js, tests/unit/inflector-test.js, tests/unit/integration-test.js
This fixes https://github.com/stefanpenner/ember-inflector/issues/94
It also adds some test additional test cases to document the current
behavior.
One additional strange bit is that the float 1.0 is returned as 1 when
concatenated into the string. I'm not sure if this is the ideal response
but I did not see any clear way to handle keeping that as 1.0 in the
returned string. This is the current behavior so changing it might
cause some unintended side-effects.
/shrug javascripts
=> Correctly pluralize floats between 1 and 2

addon/index.js
`ember-inflector` AMD module in `define.amd` environments is returning a different output format as opposed to non `define.amd` format.
cc: @rwjblue @stefanpenner @msranade
=> Return the same output format for `defined.amd` environments.

CHANGELOG.md, README.md, package.json
Now ember-inflector is managed by emberjs organization.
=> Fix to update URL to ember-inflector

addon/lib/system/inflector.js
Fixes https://github.com/emberjs/ember-inflector/pull/117.
=> Fix missing array wrapper in documentation

package.json
This addon is built-in (included by ember-data by default). We are trying to update all prebuilt addons to ember-cli-babel@6 for the ember-cli@2.13 release.
This also bumps the engine minimum (since ember-cli-babel uses ES6), and therefore will need to be a major version bump.
=> Update to use Babel 6.

addon/index.js
The CJS export could never worked without transpiling the ES6 imports above it and if you transpile them you would also transpile the ES6 exports which makes the manual CJS export pointless.
The AMD export is also unneeded since we use `ember-cli-babel` and the file is in the `addon` folder which will automatically be transpiled into AMD modules.
/cc @rwjblue
=> Remove broken AMD and CJS exports

README.md, addon/index.js, addon/lib/ext/string.js
Resolves parts of #125
/cc @rwjblue
=> Deprecate Ember.Inflector, Ember.String.singularize() and Ember.String.pluralize()

.travis.yml
Chrome's sandbox feature requires root access. My hope is that this will fix [the build for #140](https://travis-ci.org/emberjs/ember-inflector/builds/358501698):
> [0326/165542.575101:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
=> 👷 Travis: require sudo

README.md, addon/lib/helpers/pluralize.js, addon/lib/system/inflector.js, addon/lib/system/string.js, tests/unit/inflector-test.js
The `{{pluralize}}` helper accepts a count:
```hbs
{{pluralize 4 'chicken'}}
{{pluralize 1 'pig' without-count=true}}
```
This commit makes that same API available to the `inflector.pluralize()` JavaScript function.
Closes #122
Closes #124
=> ✨ inflector.pluralize accepts count, withoutCount

addon/lib/ext/string.js
Several flags (including `EXTEND_PROTOTYPES`) underneath the Ember namespace have been removed in Ember 3.2.
https://github.com/emberjs/ember.js/pull/16467
Fixed #142
=> Avoid using legacy global flags

index.d.ts
Adding this will make imports work nicely and automatically for any TypeScript consumers of the addon—no additional work required besides just installing the package!
=> Add typing definition file.

.travis.yml, package.json
```yaml
```
We have this comment on the TravisCI configuration, but the version was still stuck on `4` while ember-cli seems to have moved (go to https://github.com/ember-cli/ember-cli/find/master, press `t`, type `travis.yml` and inspect those files).
This doesn’t fix the tests yet — it only allows us to run them, since they were not running at the moment. My follow-up pull request will fix them.
=> Drop Node 4, 6, 7, 8, 9, 11, and 13 support.

.travis.yml, package.json, tests/integration/helpers/ember-inflector-test.js, yarn.lock
ember-try tests were failing release, beta and canary environments, so following the most recent [docs][docs] and with some changes to our packages, these are now fixed while maintaining other scenarios intact. To be honest, I’m new to Ember so this was mostly fixed by brute-forcing it and following the documentation — I’m happy to har some feedback about it. 😀 
[docs]: https://guides.emberjs.com/release/testing/testing-components
=> Update to ember-cli-babel@7 and fixup tests

addon/index.js
To fix this warning when using embroider:
```
WARNING in ./node_modules/ember-inflector/index.js 4:0-48
export 'defaultRules' (reexported as 'defaultRules') was not found in './lib/system' (possible exports: Inflector, pluralize, singularize)
```
=> Remove non-existing `defaultRules` re-export

addon/lib/system/inflector.js, package-lock.json, package.json
Resolves https://github.com/emberjs/ember-inflector/issues/347
mo' deps mo' problems
We can drop the (implicit / hidden) `@ember/string` dependency to simplify the dependency chain, without much hassle.
=> chore: Drop hidden ember/string dependency

ember-inflector/package.json
Seem like these got lost during conversion to v2 format
=> Restore repository and author fields in package.json

ember-inflector/src/lib/system/inflections.js
Added 'meta' to uncountable so it doesn't turn it into metum, which is not a word at least not in the typical programming sense when people use the word "meta" like "meta data" 
Tests all passed for this change. 
There was an issue mentioned previously about this usage here - https://github.com/emberjs/ember-inflector/issues/67
Which leads to the rails convention this library is keen on following. But the convention is wrong, they just refuse to fix it because it will break existing applications as mentioned here - https://github.com/rails/rails/issues/34914
Though I'm not sure why they don't just create some sort of a deprecation warning. (I'm not a rails developer) 
Anyone else who is running into this issue in the meantime can create a `inflector-rules.js` file inside of their …
=> Added meta to the uncountable array because "metum" is not a word.
